name: 'Kien & Mela'
favicon: null
layout_spectrum: 0.75587
typography_spectrum: 0.20529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070908'
    - '#77777f'
    - '#363636'
    - '#d0c2b9'
  brandStrength: 0.6552939768880606
  lightness: 0.1088010361418128
  saturation: 0.19678251957520843
  rhythmicContrast: 0.7427399950101972
purpose: []
